### PR TITLE
NewHomeworkUpdate

### PR DESCRIPTION
**Pull request by aleksei1990**
Hello please explain me what exactly wrong with that fail , didn't get?
checked everything look fine, but feel something miss
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 1.

### CODE REVIEW

**Comment by TestPro-Support** [comment]
Hello,

I’ve reviewed your homework, and I noticed that the issue seems related to how the LoginPage and HomePage objects are being instantiated. When these objects are instantiated at the class level, the WebDriver instance (getDriver()) may not be fully initialized yet, which can cause issues.

**Possible Solution:**
To ensure that the LoginPage and HomePage instances are created after the WebDriver is properly initialized, you should instantiate these page objects inside the @BeforeMethod setup or directly within the @Test method. The reason it works when you move the instantiation inside the @Test method is that by then, the WebDriver is fully initialized.
image

**Explanation:**
**Page Object Instantiation in @BeforeMethod:** By moving the instantiation of LoginPage and HomePage to the @BeforeMethod, you ensure that these objects are created after the WebDriver is fully initialized, which prevents the issue you're encountering.

If you have any questions or need further clarification, feel free to reach out. Keep up the good work!

**Comment by aleksei1990** [comment]
спасибо

**Comment by aleksei1990** [comment]
Hello trying to fix problem with POM. I added all Pages in BaseTest and still not working [cid:af474808-7514-4116-9fcc-cab8c8e0c863]

[cid:5fa75ce6-02a6-4731-89a7-4003bac432c7]
________________________________

**Comment by aleksei1990** [comment]
You meant like this

[cid:8471faf4-bf62-4d2d-ba0f-5caca460625f]
________________________________

**Pull request merged**
