### PR TITLE
Another-Update

### PR DESCRIPTION
**Pull request by aleksei1990**

### CODE REVIEW

**Comment by TestPro-Support** [comment]
Hello,

I have reviewed your homework:

The error in your code indicates that there is an issue with the BaseTest class, specifically with the initialization of the WebDriver and the BasePage objects.

The problem occurs because you are trying to initialize the BasePage objects with a null WebDriver reference. In the BaseTest class, you have the following lines:
image

The getDriver() method returns the WebDriver instance stored in the threadDriver variable, which is initialized in the launchBrowser method. However, this method is annotated with @BeforeMethod, which means it is executed before each test method. As a result, the WebDriver instance is not yet initialized when the BasePage objects are created.

To fix this issue, you can move the initialization of the BasePage objects to the launchBrowser method, as shown below:
@BeforeMethod
@Parameters({"BaseURL"})
public void launchBrowser(String BaseURL) throws MalformedURLException {
    threadDriver.set(pickBrowser(System.getProperty("browser")));
    getDriver().manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    getDriver().manage().window().maximize();
    wait = new WebDriverWait(getDriver(), Duration.ofSeconds(10));
    fluentWait = new FluentWait<WebDriver>(getDriver())
            .withTimeout(Duration.ofSeconds(5))
            .pollingEvery(Duration.ofMillis(200));
    navigateToPage(BaseURL);

    // Initialize BasePage objects here
    basePage = new BasePage(getDriver());
    loginPage = new LoginPage(getDriver());
    homePage = new HomePage(getDriver());
}

Additionally, the line systemProperty "browser", System.getProperty("browser") is commented out in your build.gradle file. This will cause an error since the pickBrowser() method in your @BeforeMethod relies on this system property. Ensure that the property is correctly set in your build.gradle file to avoid browser configuration issues.

Please also remove your commented-out code to keep your code clean and organized. Make the necessary adjustments, and your test should work. Hope it helps!
image

**Comment by aleksei1990** [comment]
hello still not working 
Screenshot 2024-09-14 185135

**Comment by TestPro-Support** [comment]
Hello,

I have reviewed your homework and have a few suggestions:

**Declare Page Objects at the Class Level:**
Declare the page objects like basePage, loginPage, homePage etc. at the class level, outside of any methods. 
image

**Initialize Page Objects in @BeforeMethod:**
After declaring the page objects at the class level, initialize them within the @BeforeMethod. This ensures that they are set up before each test method is executed.

**Remove Unnecessary or Commented Code:**
Remove any commented-out or unused code.
Commented-out browser initialization methods and old method calls.

**Comment by aleksei1990** [comment]
Thank you so much, now I got it

________________________________

**Pull request merged**
